framework:
    workflows:
        secret_invitation:
            type: 'state_machine'
            supports:
                - App\Entity\SecretSantaMember
            initial_marking: wait_approval
            marking_store:
                type: 'method'
                property: 'state'
            places:
                - wait_approval
                - approved
            transitions:
                to_approved:
                    from: wait_approval
                    to: approved

