---
services:
  server:
    container_name: secretsanta_nginx
    image: nginx:latest
    depends_on:
      - php
    networks:
      - frontend
      - secretSanta
    labels:
      - traefik.enable=true
      - traefik.docker.network=frontend
      - traefik.http.routers.secretsanta.rule=Host(`dev.secret-santa.com`)
      - traefik.http.routers.secretsanta.entrypoints=web
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html:ro,cached
  php:
    container_name: secretsanta_php
    build:
      context: docker
      dockerfile: ./Dockerfile
    networks:
      - secretSanta
    ports:
      - "9000:9000"
      - "9003:9003"
    volumes:
      - ./:/var/www/html
    extra_hosts:
      - host.docker.internal:host-gateway
    healthcheck:
      test: [ "CMD", "php", "-r", "echo 'ok';" ]
      interval: 5s
      timeout: 3s
      retries: 5

  node:
    container_name: secretesanta_node
    image: node:20
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html

  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    container_name: secretesanta_db
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: user
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "app", "-U", "app"]
      timeout: 5s
      retries: 5
      start_period: 60s
    networks:
      - secretSanta
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data:rw
  ###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    container_name: secretsanta_mailer
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - secretSanta
    labels:
      - traefik.enable=true
      - traefik.http.routers.secret-mailer.rule=Host(`mailer.secretsanta.com`)
      - traefik.http.routers.secret-mailer.entrypoints=web
      - traefik.http.services.secret-mailer.loadbalancer.server.port=8025
    ###< symfony/mailer ###

  cleancode:
#    image: jakzal/phpqa
    build:
      context: docker/cleancode
      dockerfile: ./Dockerfile
    container_name: secretsanta_cleancode
    networks:
      - secretSanta
    volumes:
      - .:/app
      - ./docker/cleancode/99-custom.ini:/usr/local/etc/php/conf.d/99-custom.ini:ro
    working_dir: /app

networks:
  frontend:
    external: true
  secretSanta:

volumes:
  db_data: