---
services:
  server:
    container_name: secretsanta_nginx
    image: nginx:latest
    depends_on:
      - php
    networks:
      - frontend
    labels:
      - traefik.enable=true
      - traefik.http.routers.secretsanta.rule=Host(`dev.secret-santa.com`)
      - traefik.http.routers.secretsanta.entrypoints=web
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html:ro,cached
  php:
    container_name: secretsanta_php
    build:
      context: docker
      dockerfile: ./Dockerfile
    networks:
      - frontend
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/html

  node:
    container_name: secretesanta_node
    image: node:20
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html

  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    container_name: secretesanta_db
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: user
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "app", "-U", "app"]
      timeout: 5s
      retries: 5
      start_period: 60s
    networks:
      - frontend
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data:rw

  phppgadmin:
    image: dockage/phppgadmin:latest
    container_name: secretesanta_phppgadmin
    depends_on:
      - database
    environment:
      SERVER_1_HOST: database
      SERVER_1_PORT: 5432
      SERVER_1_DESC: "test"
      SERVER_1_DEFAULTDB: "app"  # Doit correspondre à POSTGRES_DB
      SERVER_1_USER: "user"     # Doit correspondre à POSTGRES_USER
      SERVER_1_PASS: "password"     # Doit correspondre à POSTGRES_PASSWORD
      HIDE_pg_catalog: "false"
      HIDE_information_schema: "false"
      HIDE_pg_toast: "false"
    networks:
      - frontend
    labels:
      - traefik.enable=true
      - traefik.http.routers.secret-pma.rule=Host(`pma.secretsanta.com`)
      - traefik.http.routers.secret-pma.entrypoints=web

  ###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    container_name: secretsanta_mailer
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - frontend
    labels:
      - traefik.enable=true
      - traefik.http.routers.secret-mailer.rule=Host(`mailer.secretsanta.com`)
      - traefik.http.routers.secret-mailer.entrypoints=web
      - traefik.http.services.secret-mailer.loadbalancer.server.port=8025
    ###< symfony/mailer ###

  cleancode:
    image: jakzal/phpqa
    container_name: secretsanta_cleancode
    volumes:
      - .:/app
    working_dir: /app

networks:
  frontend:
    external: true

volumes:
  db_data: