<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20250902064741 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Update tables ids';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE member ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE member ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE secret_santa ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE secret_santa ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE task ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE task ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE token ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE token ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN token.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN token.valid_until IS \'\'');
        $this->addSql('ALTER TABLE "user" ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE "user" ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN "user".last_activity IS \'\'');
        $this->addSql('ALTER TABLE wishitem ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE wishitem ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE messenger_messages ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE messenger_messages ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN messenger_messages.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.available_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.delivered_at IS \'\'');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE member ALTER id SET DEFAULT nextval(\'member_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE member ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE messenger_messages ALTER id SET DEFAULT nextval(\'messenger_messages_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE messenger_messages ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN messenger_messages.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.available_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.delivered_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE secret_santa ALTER id SET DEFAULT nextval(\'secret_santa_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE secret_santa ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE task ALTER id SET DEFAULT nextval(\'task_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE task ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE token ALTER id SET DEFAULT nextval(\'token_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE token ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN token.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN token.valid_until IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE "user" ALTER id SET DEFAULT nextval(\'user_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE "user" ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN "user".last_activity IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE wishitem ALTER id SET DEFAULT nextval(\'wishitem_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE wishitem ALTER id DROP IDENTITY');
    }
}
