parameters:
    app.host: '%env(HOST)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $host: '%env(HOST)%'
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Services\Mailer\NewMemberMailer:
        arguments:
            $loginLinkHandler: '@security.authenticator.login_link_handler.main'

